Pdesai/ext feature
splunk-soar-connectors/exodusutility pull request #2
Opened 2022-07-01 06:16 UTC by pdesai-crest

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2022-07-07 18:58 UTC, zamastyle commented
@pdesai-crest 
I don't understand why the latest changes were added. You have added a render dictionary to an action that should not have one and added a bunch of wheels to the app. Can you explain what the purpose of these changes are? This app has been tested on several versions of the platform including the latest and none of these wheels were required for it to run properly.

2022-07-11 07:50 UTC, pdesai-crest commented
static tests are failing due to min phantom version is kept at 4.9.0 as suggested by @zamastyle

2022-07-12 20:13 UTC, alexa-phantom requested changes
There are some pretty cool actions here, but I what are your thoughts on making some fields, such as `label` and `name` custom parameters? ie finding containers under another label aside from `exodus`?

2022-07-12 20:13 UTC, alexa-phantom commented on exodus.json
> +            "description": "URL for source Phantom host",
SOAR instead of Phantom

2022-07-12 20:13 UTC, alexa-phantom commented on exodus.json
> +            "default": "https://devphantom.company.com/",
devsoar -> align with SOAR product name

2022-07-12 20:13 UTC, alexa-phantom commented on exodus.json
> +            "description": "URL for source Phantom host",
Please update all other Phantom occurrences to SOAR

2022-07-12 20:13 UTC, alexa-phantom commented on exodus.json
> +            "read_only": true,
false

2022-07-12 20:13 UTC, alexa-phantom commented on exodus.json
> +            "output": [
Possibly return data to the user?

2022-07-12 20:52 UTC, zamastyle commented on exodus.json
> +            "output": [
The sole purpose of this action is to add a specific approval artifact to the container. The artifact in itself has been enough so far. The most we could meaningfully return is the success or failure of adding the artifact and the action status essentially does that job. What did you have in mind to return?

2022-07-12 20:52 UTC, zamastyle commented on exodus.json
> +            "read_only": true,
Good fix

2022-07-12 20:52 UTC, zamastyle commented on exodus.json
> +            "default": "https://devphantom.company.com/",
good fix

2022-07-12 20:52 UTC, zamastyle commented on exodus.json
> +            "description": "URL for source Phantom host",
good fix

2022-07-12 21:08 UTC, zamastyle commented
> There are some pretty cool actions here, but I what are your thoughts on making some fields, such as `label` and `name` custom parameters? ie finding containers under another label aside from `exodus`?

The label config on a per asset basis is solid idea. I haven't seen a good use for it yet but I imagine its out there. The overall idea of the exodus label is to have a limited access container so that only authorized personnel can approve migration. That access control is left to the admin to manage. The single exodus label was just my way of injecting a requirement to add a label and consider the access limits to it. Beyond that there isn't really a good reason to limit the label an exodus asset uses.

As far as name goes, between the container creation and the container approval or rejection, the user can automate however they would like. My general expectation is that the name of the container and other specific aspects of the container would be automatically updated by an active playbook to prep it for whatever tailored review process the admin wants done.  Might be more valuable to create a dynamic name based on the name and id of the object to be migrated instead of adding an option for a different static name.

2022-07-13 12:40 UTC, pdesai-crest commented on exodus.json
> +            "description": "URL for source Phantom host",
Changes done

2022-07-13 12:40 UTC, pdesai-crest commented on exodus.json
> +            "default": "https://devphantom.company.com/",
done

2022-07-13 12:41 UTC, pdesai-crest commented on exodus.json
> +            "read_only": true,
done

2022-07-14 00:05 UTC, alexa-phantom approved these changes

2022-07-14 00:05 UTC, alexa-phantom commented on exodus.json
> +            "output": [
Not necessarily, just wanted to point out that there weren't any fields being outputted to the output table.

2022-07-15 00:53 UTC, ricardo-phantom approved these changes

2022-07-17 18:39 UTC, merged